apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/name: Elasticsearch
  name: elasticsearch-logging
spec:
  clusterIP: None
  ports:
  - name: db
    port: 9200
    protocol: TCP
    targetPort: 9200
  publishNotReadyAddresses: true
  selector:
    k8s-app: elasticsearch-logging
    name: elasticsearch-logging
  type: ClusterIP